export const cuisineList = [
  "Awadhi",
  "Mughlai",
  "Kebabs",
  "Biryani",
  "Tunday Kababi",
  "Galouti Kebab",
  "Korma",
  "Sheermal",
  "Nihari",
  "Roomali Roti",
  "Kulcha-Nahari",
  "Chaat",
  "Basket Chaat",
  "Kachori",
  "Poori-Sabzi",
  "Lassi",
  "Thandai",
  "Falooda",
  "Shahi Tukda",
  "Malai Gilori",
  "Kulfi",
  "Street Food",
  "North Indian",
  "South Indian", // Optional for diversity
];
